services:
  camera-server:
    build:
      context: .
      dockerfile: Dockerfile

    image: python:orbbec-2.1.2
    container_name: camera-server

    restart: unless-stopped

    ports:
      - "5558:5558"

    privileged: true

    volumes:
      - /dev/bus/usb:/dev/bus/usb