project:
  # 项目名称
  name: "camera-server"
  # 项目地址
  directory: "E:/projects/camera-server"

logging:
  # 日志文件名
  filename: "camera-server.log"
  # 日志等级: DEBUG INFO WARNING ERROR CRITICAL
  level: "INFO"
  # 日志留存天数
  backup_count: 30

camera:
  device_sn: "AY6966300HW"

stream:
  jpeg_quality: 85

zmq:
  # 服务端监听地址。0.0.0.0 表示允许其他主机连接。
  publisher_endpoint: "tcp://0.0.0.0:5558"
  send_hwm: 2
